services:
  - type: web
    name: fatura-kontrol
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: fatura-data
      mountPath: /app/uploads
      sizeGB: 1
